version: '3.5'
services:

  booking:
    container_name: booking
    image: jsa4000/booking-microservice:1.0.0-SNAPSHOT 
    restart: always
    hostname: booking
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8081:8081
    networks:
      - zeebe_network

  car:
    container_name: car
    image: jsa4000/car-microservice:1.0.0-SNAPSHOT
    restart: always
    hostname: car
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8083:8083
    networks:
      - zeebe_network

  flight:
    container_name: flight
    image: jsa4000/flight-microservice:1.0.0-SNAPSHOT
    restart: always
    hostname: flight
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8084:8084
    networks:
      - zeebe_network

  hotel:
    container_name: hotel
    image: jsa4000/hotel-microservice:1.0.0-SNAPSHOT
    restart: always
    hostname: hotel
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8082:8082
    networks:
      - zeebe_network

networks:
  zeebe_network:
    external:
      name: zeebe_network
