version: '3.5'
services:

  booking:
    container_name: booking
    image: jsa4000/booking-microservice:1.0.0-SNAPSHOT 
    restart: always
    hostname: booking
    network_mode: host
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8081:8081
    extra_hosts:
      mongo: 127.0.0.1
      zeebe: 127.0.0.1 
   # networks:
    #  - zeebe_network

  car:
    container_name: car
    image: jsa4000/car-microservice:1.0.0-SNAPSHOT
    restart: always
    hostname: car
    network_mode: host
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8083:8083
    extra_hosts:
      mongo: 127.0.0.1
      zeebe: 127.0.0.1
   # networks:
    #  - zeebe_network

  flight:
    container_name: flight
    image: jsa4000/flight-microservice:1.0.0-SNAPSHOT
    restart: always
    hostname: flight
    network_mode: host
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8084:8084
    extra_hosts:
      mongo: 127.0.0.1
      zeebe: 127.0.0.1
   # networks:
    #  - zeebe_network

  hotel:
    container_name: hotel
    image: jsa4000/hotel-microservice:1.0.0-SNAPSHOT
    restart: always
    hostname: hotel
    network_mode: host
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8082:8082
    extra_hosts:
      mongo: 127.0.0.1
      zeebe: 127.0.0.1
    #networks:
     # - zeebe_network

networks:
  zeebe_network:
    external:
      name: zeebe_network
