spring:
  application:
    name: flight-microservice
  profiles:
    active: local
  data:
    mongodb:
      auto-index-creation: true
      repositories.enabled: true

server:
  port: 8084
  shutdown: graceful

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint:
    health:
      show-components: always
      probes.enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health

zeebe:
  client:
    worker.defaultName: ${spring.application.name}
    job.timeout: 5000

logging:
  level:
    root: info
    org.springframework: warn

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://booking:password@localhost:27017/booking?replicaSet=rs0

zeebe:
  client:
    broker.gatewayAddress: localhost:26500
    security.plaintext: true

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://booking:password@mongo:27017/booking?replicaSet=rs0

zeebe:
  client:
    broker.gatewayAddress: zeebe:26500
    security.plaintext: true